import { Pipe, PipeTransform } from '@angular/core';

const ADMIN_LABELS: Readonly<Record<string, string>> = {
  DRAFT: 'Brouillon',
  PUBLISHED: 'Publié',
  ARCHIVED: 'Archivé',
  INFORMATION: 'Information',
  WARNING: 'Avertissement',
  QUEST_IMMINENT: 'Quête imminente',
  SUCCESS: 'Succès',
  MYSTERY: 'Mystère',
  ONLINE: 'En ligne',
  MAINTENANCE: 'Maintenance',
  UNASSIGNED: 'Non attribué',
  ADVENTURER: 'Aventurier',
  GUEST: 'Invité',
  TOP: 'Haut',
  BOTTOM: 'Bas',
  LEFT: 'Gauche',
  RIGHT: 'Droite',
  ADMIN_ALLOWED_EMAIL_CREATED: 'Administrateur autorisé ajouté',
  ADMIN_ALLOWED_EMAIL_UPDATED: 'Administrateur autorisé modifié',
  ADMIN_ALLOWED_EMAIL_DELETED: 'Administrateur autorisé supprimé',
  ADVENTURER_CREATED: 'Aventurier créé',
  ADVENTURER_UPDATED: 'Aventurier modifié',
  ADVENTURER_DELETED: 'Aventurier supprimé',
  ADVENTURERS_REORDERED: 'Aventuriers réordonnés',
  COMPANY_UPDATED: 'Compagnie modifiée',
  HOME_MESSAGE_CREATED: 'Parchemin créé',
  HOME_MESSAGE_UPDATED: 'Parchemin modifié',
  HOME_MESSAGE_ACTIVATED: 'Parchemin activé',
  HOME_MESSAGE_DELETED: 'Parchemin supprimé',
  MAP_VISION_CREATED: 'Vision de carte créée',
  MAP_VISION_UPDATED: 'Vision de carte modifiée',
  MAP_VISION_ACTIVATED: 'Vision de carte activée',
  MAP_VISION_DELETED: 'Vision de carte supprimée',
  MAP_MARKER_CREATED: 'Repère de carte créé',
  MAP_MARKER_UPDATED: 'Repère de carte modifié',
  MAP_MARKER_DELETED: 'Repère de carte supprimé',
  MEDIA_UPLOADED: 'Média ajouté',
  MEDIA_DELETED: 'Média supprimé',
  PORTAL_IDENTITY_ASSIGNMENT_UPDATED: 'Attribution de l’identité portail modifiée',
  PORTAL_IDENTITY_SUBJECT_REBOUND: 'Identité portail réassociée',
  QUEST_UPDATED: 'Quête modifiée',
  QUEST_PUBLISHED: 'Quête publiée',
  QUEST_HIDDEN: 'Quête masquée',
  QUEST_ARCHIVED: 'Quête archivée',
  QUEST_DOCUMENT_UPLOADED: 'Document de quête ajouté',
  QUEST_DOCUMENT_DELETED: 'Document de quête supprimé',
  RADAR_POINTS_IMPORTED: 'Points Radar importés',
  RADAR_POINT_UPDATED: 'Point Radar modifié',
  RADAR_POINT_DELETED: 'Point Radar supprimé',
  RADAR_TREASURE_VISIBILITY_UPDATED: 'Visibilité du trésor Radar modifiée',
  SITE_SETTINGS_UPDATED: 'Paramètres du site modifiés',
  ADMIN_ALLOWED_EMAIL: 'Adresse administrateur',
  COMPANY: 'Compagnie',
  HOME_MESSAGE: 'Parchemin',
  MAP_VISION: 'Vision de carte',
  MAP_MARKER: 'Repère de carte',
  MEDIA: 'Média',
  PORTAL_IDENTITY: 'Identité portail',
  QUEST: 'Quête',
  QUEST_DOCUMENT: 'Document de quête',
  RADAR_POINT: 'Point Radar',
  RADAR_STATE: 'État du Radar',
  SITE_SETTINGS: 'Paramètres du site',
};

@Pipe({ name: 'adminLabel' })
export class AdminLabelPipe implements PipeTransform {
  transform(value: string): string {
    return ADMIN_LABELS[value] ?? value;
  }
}
